# Generated by Django 5.0.6 on 2024-05-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(choices=[('makerere', 'Makerere'), ('kyambogo', 'Kyambogo'), ('kabaale', 'Kabaale'), ('gulu', 'Gulu'), ('muni', 'Muni'), ('soroti', 'Soroti'), ('lira', 'Lira'), ('busitema', 'Busitema'), ('mountains_of_the_moon', 'Mountains of the Moon')], max_length=50),
        ),
    ]
