# Generated by Django 5.0.6 on 2024-05-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_likes'),
        ('core', '0005_userprofile_delete_profile'),
    ]

    operations = [
    ]
