# Generated by Django 5.0.6 on 2024-05-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
